### ISSUE TITLE
Xserver Bungee freez when disabling 

### ISSUE THREAD

**Issue by przemek3697** [mickare/xserver#2]
http://pastebin.com/QTjLggS6

This log is freezing bungee while turning off

**Comment by mickare** [comment]
Hi,
which BungeeCord version do you use?

**Comment by mickare** [comment]
This exception output is normal, since I close the socket. The listening server thread is then interrupted  with that "Socket closed"-Exception. I haven't experienced any freezes so far.
My log file looks the same with the newest build-1089.

I could catch that special occurency when a shutdown happens, but printing the log is simpler.

Can you reproduce the freezing?

**Comment by przemek3697** [comment]
This error appears SOMETIMES (once few days) on my bungee freezing it totally and also i got the same error on one of my spigot servers while command /stop i can not reproduce it easily on bungee but i can type /stop on my spigot server to reproduce it everytime

**Comment by mickare** [comment]
Thanks, hiivin on spigotmc reported a similar error.
I am looking into it.
